### ISSUE TITLE
Required arguments

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#1]
Can I pass required arguments? e.g. user must pass -d or script shows error.

**Comment by maneyko** [comment]
Duplicate: see #2.

**Comment by hongkongkiwi** [comment]
This is not a duplicate because I wanted the ability to pass "required" arguments. e.g.
required arguments. I might be able to send a pull request for this. If any of the required arguments are missing, it should print an error and show the help.

```
required arguments:
  -t, --env-type=...       Type of bootloader. Can be sf, uart or sd

optional arguments:
  -d, --script-dir=...     Script directory to process and merge
  -d, --env-file=...       Env TXT file to merge
  -h, --help               Print this help message.
```

**Comment by maneyko** [comment]
Ah I understand. Thank you for clarifying. That is something the user should handle. This script purposefully does not fail on missing arguments because I think `argparse.sh` would be doing too much work.
```bash
source "argparse.sh"

arg_optional "[env-type] [t] [Script directory to process and merge]"
parse_args

if test -z "$ARG_ENV_TYPE"; then
  echo "Need to pass '-t'!"
  exit 1
fi
```

**Comment by hongkongkiwi** [comment]
In the above case, how could I print the standard help again?

I would like to show the error message and print the help again, incase of a missing argument.

**Comment by hongkongkiwi** [comment]
Ah found it!
`print_help`
