### ISSUE TITLE
[bug/feature] Escape [] characters in description

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#10]
I need to use the [] characters in my description. I am specifying a default value e.g. 

`arg_optional "[grep-regex-pattern]    [b] [Grep regex pattern to use when searching files. Default: [[space]]+]"`

Could you specify an escape character or some way so I can use these characters in the description?

**Comment by maneyko** [comment]
This works for me.

The way `argparse.sh` finds the help description is by going through the parameter long name, short name, then the help description starts at the first `[` it finds. The help description ends at the last `]` it finds from the substring not containing the first two arguments.

Example I used for testing:
```bash
#!/bin/bash

# tester.sh

source "${0%/*}/argparse.sh"

ARG_GREP_REGEX_PATTERN='[[space]]+'

arg_optional "[grep-regex-pattern] [b] [Grep regex pattern to use when searching files. Default: [[space]]+]"

arg_help     "[Example of using brackets in argument description.]"
parse_args

cat << EOT
ARG_GREP_REGEX_PATTERN: ${ARG_GREP_REGEX_PATTERN}
EOT
```
```
└[$]› ./tester.sh -h
usage:  tester.sh [-h] [-b grep-regex-pattern]

Example of using brackets in argument description.

optional arguments:
  -b, --grep-regex-pattern    Grep regex pattern to use when searching files. Default: [[space]]+
  -h, --help                  Print this help message.
```
```
└[$]› ./tester.sh -b '[[alpha]]+'
ARG_GREP_REGEX_PATTERN: [[alpha]]+
```
