### ISSUE TITLE
[bug] Argument description missing if no short argument

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#11]
This works fine
`arg_optional "[milestones-input-file] [m] [Use this as a list of input milestones.]"`

`  -m, --milestones-input-file Use this as a list of input milestones.`

However using this causes help text to disappear and screws up parsing
`arg_optional "[milestones-input-file] [Use this as a list of input milestones.]"`

Help shows up like:
`  -Manually, --milestone-title`

And this (which I think should be handled) also has some funny results
`arg_optional "[milestones-input-file] [] [Use this as a list of input milestones.]"`

Help shows up like:
`  -, --milestones-input-file Use this as a list of input milestones.`

**Comment by maneyko** [comment]
This is not supported. You should provide a long argument, short argument, and help description — anything beyond this is out-of-bounds.

I think you can get away with not providing a help description, but I haven't really tested it.

You can create a throwaway short variable `[_]` if you only want a long name — though I haven't fully tested this.
```bash
#!/bin/bash

# tester.sh

source "${0%/*}/argparse.sh"

arg_optional '[milestones-input-file] [_]'
arg_help     '[Example using throwaway short variable name.]'
parse_args

cat << EOT

ARG_MILESTONES_INPUT_FILE: ${ARG_MILESTONES_INPUT_FILE}

EOT
```
```
┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh -h
usage:  tester.sh [-h] [-_ milestones-input-file]

Example using throwaway short variable name.

optional arguments:
  -_, --milestones-input-file
  -h, --help                  Print this help message.

┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh --milestones-input-file input.txt

ARG_MILESTONES_INPUT_FILE: input.txt
┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh -_ input.txt

ARG_MILESTONES_INPUT_FILE: input.txt

```

Future work could include support for a long argument with no corresponding short argument. It seems to be within reach.
