### ISSUE TITLE
[bug] short options larger than 1 character cause weird bug

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#12]
If a short value is longer than 1 character, it causes weird parsing rules. If this is a rule, then maybe it should warn because it's a hard to track down bug in this case.

I think it should either accept short options larger than 1 character (after all they are inside [] brackets so we can know exactly how long it is, or else we should not accept anything greater than 1 character. There's no clear error when not sticking to the desired behaviour.

Here's what breaks parsing:
`arg_optional "[milestones-file] [mf] [Use this as a list of input milestones.]"`

**Comment by hongkongkiwi** [comment]
If you dont want to support short options larger than 1 character (to keep with c traditions) then we can just ignore any characters after the first for the short description. This way it would work fine and when checking with --help it would clearly show only 1 character is being used. Help would show up like:
`  -m, --milestones-file    Use this as a list of input milestones.`

Or... alternatively you could parse it as multiple short options, so it would end up being something like:
`  -m, -f, --milestones-file    Use this as a list of input milestones.`

**Comment by maneyko** [comment]
Using a short name longer than one letter is not really supported. It's up to the programmer to make sure they stay in-bounds in this respect. It does work how I'd expect, more or less, though.

Example script:
```bash
#!/bin/bash

# tester.sh

source "${0%/*}/argparse.sh"

arg_optional "[milestones-file] [mf] [Use this as a list of input milestones.]"
arg_boolean  "[flag]            [f]  [A flag]"
arg_help     "[Example using a two letter short flag.]"
parse_args

cat << EOT

ARG_FLAG:            ${ARG_FLAG}
ARG_MILESTONES_FILE: ${ARG_MILESTONES_FILE}

EOT
```
```
┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh -f

ARG_FLAG:            true
ARG_MILESTONES_FILE:

┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh -f -mf foo.txt

ARG_FLAG:            true
ARG_MILESTONES_FILE: foo.txt

┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh -fmf foo.txt

ARG_FLAG:            true
ARG_MILESTONES_FILE:

```
