### ISSUE TITLE
[bug] Argument descriptions with % in them cause printf to parse wrongly.

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#13]
Argument descriptions with % in them cause printf to parse wrongly. printf tries to parse them so they need to be escaped.

Here's an example that breaks parsing
`arg_optional "[foo] [f] [Percentage of something. Default is 100%.]"`

**Comment by maneyko** [comment]
This is indeed a tough one. I'm able to do the following at least:

Example script:
```bash
#!/bin/bash

# tester.sh

ARG_PERCENT2="100%"

source "${0%/*}/argparse.sh"

arg_optional '[percent1] [p1] [Percentage of something. Default is 100%%%%.]'
arg_optional "[percent2] [p2] [Percentage of something. Default is $ARG_PERCENT2%%%.]"
arg_help                   "[Example showing percentage in help message.]"
parse_args

cat << EOT

ARG_PERCENT1:            ${ARG_PERCENT1}
ARG_PERCENT2:            ${ARG_PERCENT2}

EOT
```
Example usage:
```
┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh -h
usage:  tester.sh [-h] [-p1 percent1] [-p2 percent2]

Example showing percentage in help message.

optional arguments:
  -p1, --percent1             Percentage of something. Default is 100%.
  -p2, --percent2             Percentage of something. Default is 100%.
  -h, --help                  Print this help message.

┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh -p2 '75%%'

ARG_PERCENT1:
ARG_PERCENT2:            75%

```

**Comment by maneyko** [comment]
I was able to make percentage signs work in https://github.com/maneyko/argparse.sh/commit/d859cada127bd072350affd7bf4c5edd51de703d in the [`argparse.sh@dev2`](https://github.com/maneyko/argparse.sh/compare/dev2) branch. Holding off on merging it with `master` do to some more testing.

**Comment by maneyko** [comment]
This should be resolved by now. @hongkongkiwi Please pull down `master` and see if it's working.
