### ISSUE TITLE
Pass arguments multiple times

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#2]
I would like to pass arguments multiple times...e.g. -d for directory
./myscript -d test1 -d test2

Is this supported?

**Comment by maneyko** [comment]
No this is not supported yet. I think you can do something like this though:
```bash
#!/bin/bash

source "argparse.sh"

arg_optional "[directory1] [d1] [First directory.]"
arg_optional "[directory2] [d2] [Second directory.]"
arg_help     "[Test two character arguments.]"
parse_args

cat << EOT
d1: $ARG_DIRECTORY1
d2: $ARG_DIRECTORY2
EOT
```
`./myscript -d2 test2`

That worked for me, but I haven't fully tested this method so I would say anything like that would be experimental.

**Comment by maneyko** [comment]
I added support for this using `arg_array` in commit https://github.com/maneyko/argparse.sh/commit/59dfa0518afd357fbcedeb1a2a9b2cf62e5d53ca. Please pull in `master` and let me know if it works for you. Thanks for the feature suggestion.

**Comment by hongkongkiwi** [comment]
./script.sh -d test1 -d test2 -d test3
test1 test3

It seems to miss argument 2.

**Comment by maneyko** [comment]
I cannot reproduce that without more information. This works for me when doing the following on `master`:
```bash
└[$]› ./usage-example.sh -d test1 -d test2 -d test3
infile:
outfile:
port-number:
outputs:
verbose:
flag:
directory:   test1 test2 test3
``

**Comment by hongkongkiwi** [comment]
Ah my mistake, I had two array arguments with the same [d] flag.

Thanks works well!

**Comment by hongkongkiwi** [comment]
This is really great! Thanks for helping with the update.
