### ISSUE TITLE
[feature request] Argument collision checking (and invalid argument checking)

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#3]
Is it possible to add argument checking? What I mean is lets say we have:
```
arg_optional "[repo-url]               [r] [Url for the upstream repository.]"
arg_optional "[readonly]               [r] [Readonly for upstream repository.]"
arg_optional "[repo-url]               [d] [Url for the downstream repository.]"
```

In this case, I have two short arguments that are the same and two long arguments that are the same. I think that the library should do a basic check and bail out in this case because it could cause unintended behaviour. I have no way to check this during my normal argument checking phase.

Obviously this is a mistake, but with large programs the short arguments especially are quite difficult to keep track of.

My other suggestion would be to spit out an error when any invalid argument strings are parsed. e.g. these would error:
* arg_optional "[[]]"
* arg_optional "]"
* arg_optional ""

**Comment by maneyko** [comment]
It is up to the developer to not provide two arguments with the same long name or short name. A main goal of this project is speed/efficiency. I think too many checks on invalid arguments from the user would be a waste of time and would slow things down. Anyways, why on Earth would the user do `arg_optional "lo[ng]-parameter"`? This type of behavior is obviously not supported.

If you want to create multiple long arguments, I would recommend creating a "throwaway" short argument for now like the following:
```bash
source "$(dirname "$0")/argparse.sh"

arg_boolean    "[flag]        [x] [My important flag]"
arg_optional   "[flag2]       [x] [My second important flag]"
arg_optional   "[flag3]       [x] [My third important flag]"
```
Then you can do the following from the command line:
```bash
./usage-example.sh --flag2 23 --flag3 21 --flag
```
