### ISSUE TITLE
[feature request] Support = after arguments and quotes

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#4]
If possible, I would like to support "=" after arguments as well as double quote support? This is a standard way of passing arguments and makes it easier sometimes than relying on spaces.

e.g. it would be something like:
* --repo-url=git://git@github.com
* --repo-url="git://git@github.com"
* "--repo-url"=git://git@github.com
* "--repo-url"="git://git@github.com"

**Comment by maneyko** [comment]
Agreed, supporting arguments with spaces is a goal of this project. The following would be ideal
```bash
arg_optional   "[sentence] [s] [A sentence to print.]"
```
```
./usage-example.sh --sentence 'The cat in the hat'
```

**Comment by maneyko** [comment]
Update: arguments with spaces seem to be working now. Not sure exactly when this started working ¯\\\_(ツ)_/¯
```bash
#!/bin/bash

# tester.sh

source "${0%/*}/argparse.sh"

arg_positional '[infile]'
arg_optional   '[sentence] [_]'
parse_args

cat << EOT

ARG_INFILE:   ${ARG_INFILE}
ARG_SENTENCE: ${ARG_SENTENCE}

EOT
```
```
┌─[maneyko:@MBP.local:~/scripts/argparse/argparse.sh:master]
└[$]› ./tester.sh --sentence "The cat in the hat." input-file.txt

ARG_INFILE:   input-file.txt
ARG_SENTENCE: The cat in the hat.

```
Still need to think about using equals sign `=` for long variable assignment. I just haven't really had a use case to specifically use it.

**Comment by maneyko** [comment]
This has been resolved. `--long-flag='some value'` is now supported.
