### ISSUE TITLE
[feature request] Handle missing or additional short arguments

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#5]
There has been a couple of cases where I've accidentally left out a short argument and it has broke the parsing a bit.

It would be great if the short version of arguments and description were optional. And also, if I could provide more than one short argument.

So I am thinking these cases would all work
* arg_optional "[repo-url] [url] [u] [Url for the upstream repository.]"
* arg_optional "[server-url] [Url for the server.]"
* arg_optional "[password]"

**Comment by maneyko** [comment]
See https://github.com/maneyko/argparse.sh/issues/3#issuecomment-791986249. Passing long arguments with no corresponding short arguments is a goal of this project.

**Comment by hongkongkiwi** [comment]
When using a long argument with no corresponding short argument specified, the help text disappears. Perhaps it's eaten by the short argument?

e.g.
`arg_optional "[grep-regex-pattern]    [b] [Grep regex pattern to use when searching files.]"`

vs 
`arg_optional "[grep-regex-pattern] [Grep regex pattern to use when searching files.]"`

**Comment by maneyko** [comment]
Only passing long arguments is not supported for now. You can do the hack described in https://github.com/maneyko/argparse.sh/issues/3#issuecomment-791986249 to get this functionality.
