### ISSUE TITLE
[feature request] Neaten output columns

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#6]
I have some long arguments and descriptions. For example:
```
optional arguments:
  -f, --build-file         Local file to copy to upstream repository.
  -u, --remote-file        Name and path of the file in upstream repository.
  -t, --tags-access-token  Used for pulling this repo latest tag from Gitlab API.
  -r, --repo-url           Url for the upstream repository.
  -p, --repo-access-token  Access token for the upstream repository.
  -b, --repo-base-path     Base path to use in upstream repository.
  -h, --repo-app-versions-file Filename in repo containing app versions. Default app_versions.json.
  -d, --no-gitlab-tags-api Do not try to use tags api if tags-access-token is passed.
  -e, --no-app-version-check Disable checking app version matches git repo tag version.
  -n, --repo-pull-submodules Pull upstream submodules after cloning.
  -d, --no-repo-version-update Disable updating of the app_versions.json file. This is not recomomended.
  -s, --silent             Silence all log messages.
  -v, --verbose            Show verbose log messages.
  -h, --help               Print this help message.
```

It would be nice if the columns and text were all aligned together. `column` is the command line tool for this.

I understand that you might not want to add dependencies to the script, so in this case, I could suggest two options:
1. We could write a bash only tool like column (this seems a bit wasteful but is an option)
2. We could add an optional dependency by using a command line this:
`command -v "column" >/dev/null 2>&1 && COLUMN_INSTALLED=true ` if it's installed we could use it for formatting, if it's not installed we can use the current formatting.
3. There could be a way for me to parse the help output somehow so I can do some formatting myself.

I think my preference is 2 if your ok to add column as an optional depdency.

**Comment by maneyko** [comment]
I tested this and getting `column` to work with colors was a bit difficult. I will look in to creating a global variable to adjust the default column width. It is hard-coded right now.

**Comment by hongkongkiwi** [comment]
Awesome! Looking forward to trying to the new version when it's ready.

**Comment by maneyko** [comment]
Feature has been added in https://github.com/maneyko/argparse.sh/commit/62b3aef6cda3d1b8c9f7619114a1fae475498a6d. Example of usage in https://github.com/maneyko/argparse.sh/commit/f423a4f349b73a6b5b729f89243c5ae371ff03c3.

Thanks for your suggestion!

**Note**: For the sake of speed, any call to a non-Bash program is strongly discouraged. For example, I swapped `$(echo $var | tr 'a-z-' 'A-Z_')` (convert `heLLo-world` to `HELLO_WORLD`) in favor of pure Bash string substitution in https://github.com/maneyko/argparse.sh/commit/b0d45261f5166714866cd7c72bcb3a2c92b7ed98 and saw a huge speed increase of `argparse.sh`. An example benchmark for this:
```bash
#!/bin/bash

get_name_upper() {
  res="${1//-/_}" ; res="${res//a/A}" ; res="${res//b/B}" ; res="${res//c/C}" ; res="${res//d/D}" ;
  res="${res//e/E}" ; res="${res//f/F}" ; res="${res//g/G}" ; res="${res//h/H}" ; res="${res//i/I}" ;
  res="${res//j/J}" ; res="${res//k/K}" ; res="${res//l/L}" ; res="${res//m/M}" ; res="${res//n/N}" ;
  res="${res//o/O}" ; res="${res//p/P}" ; res="${res//q/Q}" ; res="${res//r/R}" ; res="${res//s/S}" ;
  res="${res//t/T}" ; res="${res//u/U}" ; res="${res//v/V}" ; res="${res//w/W}" ; res="${res//x/X}" ;
  res="${res//y/Y}" ; name_upper="${res//z/Z}"
}

STR='heLLo-world'

echo "Benchmarks for bash capitalization:"
time for i in {1..5000}; do
  get_name_upper "$STR"
  result="$name_upper"
done

echo "Benchmarks for 'tr' capitalization:"
time for i in {1..5000}; do
  result="$(echo "$STR" | tr 'a-z-' 'A-Z_')"
done
```
```
Benchmarks for bash capitalization:

real    0m1.011s
user    0m1.007s
sys     0m0.003s
Benchmarks for 'tr' capitalization:

real    0m14.411s
user    0m5.209s
sys     0m9.980s
```
