### ISSUE TITLE
[feature request] Handle missing closing "]" in argument parsing.

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#7]
I have had a case where I forgot to add a closing ]" in my argument string.

It caused some weird problems that took me a while to debug.

I am thinking that it would be a great idea to gracefully handle this case. I think in the case of any argument passed it should automatically close it with a ] in the case that the user forgot to pass it.

```
arg_array "[build-file] [f] [Local file to copy to upstream repository."
arg_optional "[tags-access-token] [t] [Used for pulling this repo latest tag from Gitlab API."
arg_boolean "[no-gitlab-tags-api] [d] [Do not try to use tags api if tags-access-token is passed."
```

we could do a check by adding a simple:
`[ "${str: -1}" != "]" ] && str="${str}]"`

**Comment by maneyko** [comment]
This will add extra checks and slow things down. Just code it the right way.
