### ISSUE TITLE
[feature request] Add magic array variable for additional invalid arguments

### ISSUE THREAD

**Issue by hongkongkiwi** [maneyko/argparse.sh#9]
Sometimes I have a problem where I will modify the script arguments. For example, originally I had --foo and I change it to --bar. But the script accepts -foo and doesn't tell me anything so I need to do some debugging.

It would be great to have a magic variable that I can check to show some useful errors. So in the above example:
`EXTRA_INVALID_ARGS=("--foo")`

That way I can loop through them and warn the user that these are not valid command line arguments.

**Comment by maneyko** [comment]
These should be stored in the global array `POSITIONAL`.

**Comment by maneyko** [comment]
Still applies: https://github.com/maneyko/argparse.sh/issues/9#issuecomment-794038496.
